{% set name = "doconce" %}
{% set version = "1.5.9" %}
{% set sha256 = "ca0f101bfe42d44b0b0ce5bb10a1cc2294905b200e487ee58e11597bce72e424" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/doconce/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pygments
    - future
    - preprocess
    - mako
  host:
    - python
    - pip
  run:
    - python
    - pygments
    - notebook
    - tornado
    - pyzmq
    - traitlets
    - pickleshare
    - jsonschema
    - future
    - mako
    - python-levenshtein
    - libxml2 2.9.*
    - libxslt
    - zlib 1.2.*
    - lxml
    - sphinx
    - alabaster
    - sphinx_rtd_theme
    - cloud_sptheme
    - sphinx_bootstrap_theme
    - paver
    - cogapp
    - beautifulsoup4
    - html5lib
    - texinfo  # [not win]
    - pandoc
    - sphinxcontrib-paverutils
    - sphinxjp.themes.solarized
    - preprocess
#    - sphinxjp.themes.impressjs    # incompatible with sphinx >= 1.7
    - publish
# FIXME: Add these packages when available in conda
#    - pdftools
#    - sphinx-sagecell
#    - tinkerer
#    - pygments-ipython-console
#    - pygments-doconce
#    - ptex2tex

test:
  imports:
    - doconce

about:
  home: http://doconce.github.io/doconce/doc/web/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Document once, include anywhere

  description: |
    DocOnce is two things:
    .
    1. DocOnce is a very simple and minimally tagged markup language that
    looks like ordinary ASCII text (much like what you would use in an
    email), but the text can be transformed to numerous other formats,
    including HTML, Wiki, LaTeX, PDF, reStructuredText (reST), Sphinx,
    Epytext, and also plain text (where non-obvious formatting/tags are
    removed for clear reading in, e.g., emails). From reStructuredText
    you can go to XML, HTML, LaTeX, PDF, OpenOffice, and from the latter
    to RTF and MS Word. From Pandoc one can generate Markdown, reST,
    LaTeX, HTML, PDF, DocBook XML, OpenOffice, GNU Texinfo, MediaWiki,
    RTF, Groff, and other formats.
    .
    2. DocOnce is a working strategy for never duplicating information.
    Text is written in a single place and then transformed to a number of
    different destinations of diverse type (software source code,
    manuals, tutorials, books, wikis, memos, emails, etc.). The DocOnce
    markup language support this working strategy. The slogan is: "Write
    once, include anywhere".
  doc_url: http://doconce.github.io/doconce/doc/web/
  dev_url: https://github.com/doconce/doconce

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
    - aless80
