travis:
  secure:
    BINSTAR_TOKEN: cKnm74jUeliRiFeBF5nm7Mn9px0fohSz+rKa6LYGKnT4jelX7ZZdLXliFXR23hdozyOuLUowRglTeKtrv6T7Jb0v2do1Tdz67y8fi4MVNOGE5te+UC5JqpTLB1GvgcQ+TCH4l0B+/0WY6iKr2F/IMzVsMgL00T/ATxhkPFSDqjeSzsh1b0WPXvKOoHFTkh10vLSGwH5GOiROJlPyefSNtMfnt3ytJ4cYO61/iKjBU9Mj9rGE3eQoAvM4sZZu1ye1MHSI5V+RMxpJd2Fgkdrwyl22Kw+00hg4gAMOzHz8VCkd2lS0aXirPKRN7DOqiJwqL9eOihlxqIC6xCH6eGsEwwipZMO2d+sVaW4xYn5lof1HiYf20eBkD0R/DdBheMXPOIdN6DbL0Xi1UrD9An7bdDd35jXN6XC7gabECcJ0BHauKRbbMye+7WLw0hVkvJv/FRyQ8lRrP6ALUG/DIS4qnAomxsBFjiQGDicpfjxo3pPIvQrZCm7KGM11Bv015QRK+1zTGn8PKMJpUL2EdPu3AfMaegoKf1avqIgO8MU1NpLwuiQJieGjAw6WKKtUPD2rGN+ItoVzv4HHSrlDHJMTSmBjm807hXWX5qXBjQ+u1RVWfFQFIGXug/bn9qPaggNrRdWAZu5AyTsXjpVpOJidwn5AUrHZQh9ecvV1c1jisck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
